[workspace]
resolver = "2"
members = [
  "actor",
  "actor/derive",
  "cli",
  "cli/derive",
  "client",
  "client_cli",
  "config",
  "config/derive",
  "core",
  "core/test_network",
  "crypto",
  "tools/kura_inspector",
  "tools/parity_scale_decoder",
  "tools/kagami",
  "data_model",
  "data_model/primitives",
  "ffi",
  "ffi/derive",
  "futures",
  "futures/derive",
  "logger",
  "macro",
  "macro/derive",
  "p2p",
  "permissions_validators",
  "schema",
  "schema/gen",
  "schema/derive",
  "substrate",
  "telemetry",
  "version",
  "version/derive",
]

[profile.release-with-debug]
inherits = "release"
debug = true
