[package]
name = "iroha_telemetry_derive"
version = "2.0.0-pre-rc.6"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
description = "Tracking metrics in iroha_core, requires some instrumentation that is most conveniently expressed as attribute-like macros."
edition = "2021"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger", "iroha", "model"]
categories = ["cryptography::cryptocurrencies", "api-bindings"]

[lib]
proc-macro = true

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }


[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = { version = "1.0" }
proc-macro2 = "1.0"
proc-macro-error = "1.0"

[dev-dependencies]
iroha_core = { version = "=2.0.0-pre-rc.6", path = "../../core" }

trybuild = "1.0.53"
