[package]
name = "iroha_derive"
version = "2.0.0-pre-rc.6"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
iroha_macro = { version = "2.0.0-pre-rc.6", path = ".." }

trybuild = "1.0.53"
