name: I2::Dev::Deploy

on:
  push:
    branches: [iroha2-dev]

env:
  CARGO_TERM_COLOR: always

# Note jobs in this workflow are run on `push` meaning that there's
# no point in burning our AWS self-hosted runners' time. Hence
# `ubuntu-latest` and not `[self-hosted, Linux]`.
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: set up buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hyperledger/iroha2:dev
          build-args: |
            TARGET_DIR=release
            PROFILE=--release
      - name: Build and push docker image (iroha_client_cli)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hyperledger/iroha2:client-cli-dev
          build-args: |
            TARGET_DIR=release
            PROFILE=--release
            BIN=iroha_client_cli
      - name: Build and push docker image (kagami)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hyperledger/iroha2:kagami-dev
          build-args: |
            TARGET_DIR=release
            PROFILE=--release
            BIN=kagami

      - name: Build and push docker image (load-rs:dev)
        run: |
          sleep 10s
          echo "wait to other workflow"
      - uses: convictional/trigger-workflow-and-wait@v1.6.0
        with:
          owner: soramitsu
          repo: iroha2-longevity-load-rs
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: load-rs-push-from-dev.yaml
          ref: dev

  build-ci-image:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push Docker container
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.ci
          tags: hyperledger/iroha2-ci:latest
          push: true

  archive-and-publish-schema:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: mold --run cargo build --release --verbose
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: cargo-build-release
          path: target/release/iroha
      - name: Archive Client CLI build
        uses: actions/upload-artifact@v2
        with:
          name: cargo-client-cli-build-release
          path: target/release/iroha_client_cli
      - name: Archive Crypto CLI build
        uses: actions/upload-artifact@v2
        with:
          name: cargo-crypto-cli-build-release
          path: target/release/kagami
      - name: Run schema generation
        run: |
          mkdir -p target/schema
          cargo run --bin kagami -- schema >target/schema/schema.json
      - name: Upload schema
        uses: actions/upload-artifact@v2
        with:
          name: schema
          path: target/schema

  print-telemetry:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Run debug tests and save telemetry
        env:
          TELEMETRY_FILE: ../target/telemetry/debug.json.lz4
        run: |
          mkdir -p target/telemetry
          cargo test -p iroha_client --all-features -- unstable_network || true
      - name: Run release tests and save telemetry
        env:
          TELEMETRY_FILE: ../target/telemetry/release.json.lz4
        run: mold --run cargo test -p iroha_client --all-features --release -- unstable_network || true
      - name: Install script dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends lz4 jq
      - name: Print debug telemetry info
        run: |
          ./scripts/analyze_telemetry.sh target/telemetry/debug.json.lz4 >target/telemetry/debug.md
      - name: Print release telemetry info
        run: ./scripts/analyze_telemetry.sh target/telemetry/release.json.lz4 >target/telemetry/release.md
      - name: Print debug telemetry info
        run: |
          echo '## Debug build'
          cat target/telemetry/debug.md
      - name: Print release telemetry info
        run: |
          echo '## Release build'
          cat target/telemetry/release.md
      - name: Create telemetry comment
        uses: actions-ecosystem/action-create-comment@v1
        with:
          body: |
            \# Telemetry info
            \## Debug build
            ${{ steps.debug-telemetry.outputs.body }}
            \## Release build
            ${{ steps.release-telemetry.outputs.body }}
          github_token: ${{ secrets.github_token }}
        continue-on-error: true
      - name: Archive telemetry
        uses: actions/upload-artifact@v2
        with:
          name: telemetry
          path: target/telemetry
